object Versions {
    const val kotlinVersion = ""
    const val coreKtxVersion = "1.6.0"
    const val appcompatVersion = "1.3.0"
    const val materialVersion = "1.4.0"
    const val constraintlayoutVersion = "2.0.4"
    const val junitVersion = "4.13.2"
    const val extjunitVersion = "1.1.3"
    const val espressocoreVersion = "3.4.0"
    const val hiltVersion = "2.42"
    const val hiltViewModelVersion = "1.0.0-alpha01"
    const val navigationVersion = "2.5.1"
    const val retrofit2Version = "2.9.0"
    const val coroutineVersion = "1.3.6"
    const val lifecycleVersion = "2.5.1"
    const val logginInterceptorVersion = "4.9.0"
    const val activityVersion = "1.1.0"
    const val fragmentVersion = "1.2.5"
    const val glideVersion = "4.13.2"
    const val exoplayerVersion = "2.14.1"
    const val mockVersion = "1.11.0"
    const val archCoreVersion = "2.1.0"
    const val coroutinesTestVersion = "1.5.0"
    const val roomVersion = "2.3.0"
    const val compose_version = "1.2.0"
    const val compose_activity_version = "1.5.1"
    const val compose_navigation_version ="2.5.1"

}